services:
  - type: web
    name: savenshare
    runtime: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
